Add options for other sample rates
chirp/chirp-embedded-examples pull request #11
Opened 2019-12-05 15:59 UTC by joextodd

- Fixed bug when using other sample rates on the STM32F4, the problem was with the PDM module. The PDM buffer size is hardcoded and used by the audio driver, so we need to change the value in the header to allocate the correct buffer size. 

- STM32F4 is now detecting the correct frequencies at 44.1kHz and 48kHz, however still not decoding - perhaps not processing fast enough.

- Also set the STM32F7 project to use 44.1kHz by default now, this works for sending and receiving, and with the embedded ultrasonic protocol.

2019-12-05 16:40 UTC, LittleMonsterFr approved these changes
Great to have the correct frequencies ! There is however for sure enough processing power on the F4, something else must be wrong

2019-12-05 16:40 UTC, LittleMonsterFr commented on stm32f469i-discovery/src/application.c
> +	if (sample_rate == 16000) {
Opening brackets on a new line please =P

2019-12-05 16:40 UTC, LittleMonsterFr commented on stm32f746g-discovery/src/main.c
> +				short_play_buffer[play_buffer_offset + i * 2 + 1] = value;
Nice !

2019-12-05 16:43 UTC, LittleMonsterFr requested changes
I approved by mistake - one little thing to fix

2019-12-05 16:45 UTC, joextodd commented
Yep it works now! Looks like the correction values just needed tweaking a little bit more

2019-12-09 09:53 UTC, LittleMonsterFr approved these changes

2019-12-09 09:53 UTC, merged